import { toHexRows } from "./formatHex";

describe("toHexRows", () => {
  it("shows only printable generated bytes in the ASCII column", () => {
    const [row] = toHexRows(new Uint8Array([0x00, 0x00, 0x00, 0x41, 0x31, 0x7e, 0x7f]));

    expect(row.ascii).toBe("...A1~.");
  });
});
