import { toHexRows } from "./formatHex";

describe("toHexRows", () => {
  it("shows only printable generated bytes in ASCII mode", () => {
    const [row] = toHexRows(new Uint8Array([0x00, 0x00, 0x00, 0x41, 0x31, 0x7e, 0x7f]));

    expect(row.decodedText).toBe("...A1~.");
  });

  it("decodes UTF-8 text and replaces control bytes with dots", () => {
    const bytes = new Uint8Array([0xe9, 0x80, 0x9a, 0xe4, 0xbf, 0xa1, 0x00]);

    expect(toHexRows(bytes, 16, "utf-8")[0].decodedText).toBe("通信.");
  });

  it("decodes Shift_JIS text and replaces control bytes with dots", () => {
    const bytes = new Uint8Array([0x92, 0xca, 0x90, 0x4d, 0x00]);

    expect(toHexRows(bytes, 16, "shift_jis")[0].decodedText).toBe("通信.");
  });

  it("keeps a Shift_JIS character intact across a row boundary", () => {
    const bytes = new Uint8Array([...Array(15).fill(0x41), 0x92, 0xca]);
    const rows = toHexRows(bytes, 16, "shift_jis");

    expect(rows[0].decodedText).toBe("A".repeat(15));
    expect(rows[1].decodedText).toBe("通");
  });

  it("shows malformed encoded sequences as dots", () => {
    expect(toHexRows(new Uint8Array([0x92]), 16, "shift_jis")[0].decodedText).toBe(".");
  });
});
